### PR TITLE
Add bash completion for `git cms-addpkg`

### PR DESCRIPTION
**Pull request by fwyzard**
The completion is available for both `git-cms-addpkg` and `git cms-addpkg`.

### CODE REVIEW

**Comment by smuzaffar** [comment]
@fwyzard , sorry I missed this. 

I have tested it locally and it works fine if I have already done it `git cms-init` and I am in `src` directory. As all `git-cms` tools are suppose to work under `cmsenv` so may be if one is not under `src` then first do a `cd $CMSSW_BASE` ?

**Comment by fwyzard** [comment]
> As all `git-cms` tools are suppose to work under `cmsenv` so may be if one is not under `src` then first do a `cd $CMSSW_BASE` ?

Good point.

**Comment by smuzaffar** [comment]
Also can you please move it under `share/etc/profile.d/S99cms-git-tools-completion.sh` . Then we can just rsync this `share/etc/profile.d` to `/cvmfs/cms.cern.ch/share/etc/profile.d` which contains the scripts automatically sources by `cmsset_default.sh`

**Comment by fwyzard** [comment]
Just to double check, I should create a new directory `share/etc/profile.d/` and move the file there, correct ?

**Comment by smuzaffar** [comment]
> Just to double check, I should create a new directory `share/etc/profile.d/` and move the file there, correct ?

yes, that is correct.
By the way, does this work for CentOs7 ? I get strange results when run under cc7 releases ( may be it is git or bash version issue)

**Comment by fwyzard** [comment]
I've made three changes:
  - moved the script to `share/etc/profile.d/S99cms-git-tools-completion.sh`;
  - if `$CMSSW_BASE` is defined and `$CMSSW_BASE/src/.git` exists, take the list of packages from Git;
  - otherwise, if `$CMSSW_RELEASE_BASE` is defined and `$CMSSW_RELEASE_BASE/src` exists, take the list of packages from the release area.

**Comment by fwyzard** [comment]
From a quick test on El7 (in a `cmssw-el7` container), the completion for `git-cms-addpkg` is working, while the completion for `git cms-addpkg` does not work.

But I don't get any completion for any of the native `git` commands, either.

**Comment by fwyzard** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

this needs to be tested via cmsdist PR (with changes to deploy this new script)

**Pull request merged**
