### PR TITLE
Add scripts to fetch or show the content of a pull request

### PR DESCRIPTION
**Pull request by fwyzard**
#### `git-cms-fetch-pr`
Fetches the pull request to a local branch, named after the PR number

#### `git-cms-show-pr`
Shows the commit that compose the pull request

#### `git-cms-cherry-pick-pr`
Cherry-picks the commit that compose the pull request

### CODE REVIEW

**Comment by smuzaffar** [comment]
@fwyzard , why not use github api https://developer.github.com/v3/pulls/#list-commits-on-a-pull-request to show pull requests commits?

**Comment by smuzaffar** [comment]
looks like you missed to add `git-cms-cherry-pick-pr`

**Comment by fwyzard** [comment]
> looks like you missed to add `git-cms-cherry-pick-pr`

ops, too many branches... should be there now

**Comment by fwyzard** [comment]
do you think it would be useful to add a `-a` option to `git cms-cherry-pick-pr` to call `git cms-checkdeps -a` ?

**Comment by fwyzard** [comment]
> @fwyzard , why not use github api https://developer.github.com/v3/pulls/#list-commits-on-a-pull-request to show pull requests commits?

That's an interesting idea.

However, it would take me some time to understand how to use it and integrate it in the script,  and I don't think I will be able to do any time soon.

So, I would suggest to open an issue to keep track of it, but of course I'd be happy if somebody else steps in to do it :-)

**Comment by smuzaffar** [comment]
@fwyzard , can you please add the man-pages for these three new commands https://github.com/cms-sw/cms-git-tools/tree/master/docs/man/man1 ?

**Pull request merged**
