### PR TITLE
propagate documentation updates

### PR DESCRIPTION
**Pull request by kpedro88**
I finally figured out the right way to propagate man page updates here:
* edit the files in `doc/man`
* run `make` -> updates the files in `doc/man/man1`

I touched all the files (to pull in earlier updates that hadn't been propagated with `make`) and made a few more fixes.

### CODE REVIEW

**Comment by smuzaffar** [comment]
@kpedro88 , I do not remember why this was not done with in spec file. I would suggest to drop all the generated files and we run `make` during build.

**Comment by kpedro88** [comment]
@smuzaffar yes, that would make more sense. I updated this PR to remove the generated files, and updated the makefile to create the output dir before trying to fill it (while ignoring it in .gitignore).

**Comment by kpedro88** [comment]
can you update the spec file?

**Comment by smuzaffar** [comment]
spec is updated : https://github.com/cms-sw/cmsdist/pull/3837

**Pull request merged**
